#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.290c08e8f15caaf4dc06a7bd5bca4eb0995b0b79.name = "1.0~ynh1"
    test_upgrade_from.c06c6b5e4c5042f61fc855c60a9ad5cd123f405f.name = "Upgrade from 1.924~ynh2"
