test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.ca4d54e5e6c1bc7d772e375f6193b46f886034a5.name = "Upgrade from 1.0"
    