#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --log="$data_dir/DATA/LOG/yacy00.log"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Configuring Yacy..."

ynh_systemctl --service="$app" --action="start" --log_path="$data_dir/DATA/LOG/yacy00.log" --wait_until="Started httpd:"

ynh_exec_as_app YACY_DATA_PATH="$data_dir/DATA" "$install_dir/bin/passwd.sh" "$password"

ynh_systemctl --service="$app" --action="stop" --log_path="$data_dir/DATA/LOG/yacy00.log"

ynh_replace --file="$data_dir/DATA/SETTINGS/yacy.conf" \
    --match="promoteSearchPageGreeting.homepage=https://yacy.net" \
    --replace="promoteSearchPageGreeting.homepage=https://$domain$path"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path="$data_dir/DATA/LOG/yacy00.log" #--wait_until="Started httpd:"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
