#!/bin/bash

#Remove official Debian package
sudo apt-get remove yacy -y -qq

#Remove YaCy service to YunoHost monitoring
sudo yunohost service remove yacy

#Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
