#!/bin/bash

# Remove Debian official paquage
sudo apt-get remove yacy

# Remove YaCy service to the YunoHost monitoring
sudo yunohost service remove yacy --log /var/log/yacy/yacy00.log

sudo service nginx reload
sudo yunohost app ssowatconf 
